/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GetHelpRouteImport } from './routes/get-help'
import { Route as FoundryRouteImport } from './routes/foundry'
import { Route as FamilyServicesRouteImport } from './routes/family-services'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdultServicesRouteImport } from './routes/adult-services'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const GetHelpRoute = GetHelpRouteImport.update({
  id: '/get-help',
  path: '/get-help',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundryRoute = FoundryRouteImport.update({
  id: '/foundry',
  path: '/foundry',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyServicesRoute = FamilyServicesRouteImport.update({
  id: '/family-services',
  path: '/family-services',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultServicesRoute = AdultServicesRouteImport.update({
  id: '/adult-services',
  path: '/adult-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adult-services': typeof AdultServicesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/family-services': typeof FamilyServicesRoute
  '/foundry': typeof FoundryRoute
  '/get-help': typeof GetHelpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adult-services': typeof AdultServicesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/family-services': typeof FamilyServicesRoute
  '/foundry': typeof FoundryRoute
  '/get-help': typeof GetHelpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adult-services': typeof AdultServicesRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/family-services': typeof FamilyServicesRoute
  '/foundry': typeof FoundryRoute
  '/get-help': typeof GetHelpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adult-services'
    | '/contact'
    | '/donate'
    | '/family-services'
    | '/foundry'
    | '/get-help'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adult-services'
    | '/contact'
    | '/donate'
    | '/family-services'
    | '/foundry'
    | '/get-help'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adult-services'
    | '/contact'
    | '/donate'
    | '/family-services'
    | '/foundry'
    | '/get-help'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdultServicesRoute: typeof AdultServicesRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  FamilyServicesRoute: typeof FamilyServicesRoute
  FoundryRoute: typeof FoundryRoute
  GetHelpRoute: typeof GetHelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/get-help': {
      id: '/get-help'
      path: '/get-help'
      fullPath: '/get-help'
      preLoaderRoute: typeof GetHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundry': {
      id: '/foundry'
      path: '/foundry'
      fullPath: '/foundry'
      preLoaderRoute: typeof FoundryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-services': {
      id: '/family-services'
      path: '/family-services'
      fullPath: '/family-services'
      preLoaderRoute: typeof FamilyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult-services': {
      id: '/adult-services'
      path: '/adult-services'
      fullPath: '/adult-services'
      preLoaderRoute: typeof AdultServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdultServicesRoute: AdultServicesRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  FamilyServicesRoute: FamilyServicesRoute,
  FoundryRoute: FoundryRoute,
  GetHelpRoute: GetHelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
